### PR TITLE
Aditya views

### PR DESCRIPTION
**Pull request by aditya7496**
Please review and merge with develop.

- Issue around registration errors may stem from server side, similar error EJS tags in login seems to work, still looking at it. 
- The login and reg pages have been updated and require final touch once reg error message issue if fixed. 
- Admin User management page is done, and user navigation menu is partially completed, but still needs to be updated.
- User Content page created, but still requires little more work,
- User homepage may need some major changes to look more like H5P hub that Ben wanted done, currently analyzing.

### CODE REVIEW

**Comment by BoulterJackson** [comment]
dismissed CodeQL warnings/suggestions, most (if not all) of them are addressed in a different branch

**Comment by BoulterJackson** [comment]
can ignore the CodeQL warnings/suggestions, most of the issues are addressed in a different branch

**Comment by BoulterJackson** [comment]
merge conflicts have been fixed

**Review by tahmed2 — COMMENTED** [review]
Looks good

**Pull request merged**
